version: '3.8'

volumes:
  datafiles:

services:
  database:
    image: mysql
    volumes:
      - datafiles:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_trade

  api:
    build:
      context: ./0auth
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5184:8080"
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=server=database;username=root;password=1234;database=db_trade