version: "4.34"

volumes:
  my-datavolume:

services:
  db:
    image: mysql:8.0
    volumes:
      - my-datavolume:/var/lib/mysql 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234" 
      MYSQL_DATABASE: db_trade 
    networks:
      - my-network


  api:
    build:
      context: C:\Users\HASH\source\repos\0auth\0auth
      dockerfile: Dockerfile
    depends_on:
      - db
    ports: 
      - "3000:8080"
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my-network


networks:
  my-network: